### ISSUE TITLE
add prometheus label.

### ISSUE THREAD

**Issue by WangHL0927** [nuvo/emq_exporter#14]
I recommend using the label function of prometheus for similar data aggregation. Label is very useful for query and data calculations. The current data items are independent, and configuring the dashboard is not convenient.

**Comment by hagaibarel** [comment]
This is something that can be achieved using Prometheus scrape jobs and adding/re-labeling. Since everyone has a slightly different setup and requirements (i.e. in k8s cluster, stand alone etc.) I think it's best to leave that decision to the Prometheus admin
