### ISSUE TITLE
"emq_nodes_metrics_packets.publish.received" is not a valid metric name

### ISSUE THREAD

**Issue by radumazi** [nuvo/emq_exporter#17]
Hello, I am getting these kind of errors since updating to emqx v3.2.0. From what I can see this is just a matter of emqx publishing metric names with . instead of / , should be an easy fix. Let me know if you are still maintaining this, I can do a pull request.

Thank you,
Radu

**Comment by hagaibarel** [comment]
Merged into v0.4.2, give it a go an let me know

**Comment by radumazi** [comment]
@HagaiBarel Thanks for letting me know
